---
driver:
  name: vagrant
  customize:
    memory: 512
    cpus: 1
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
  data_bags_path: "data_bags"
  encrypted_data_bag_secret_key_path: "data_bags/encrypted_data_bag_secret"
  roles_path: "roles"
  environments_path: "environments"

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1
  client_rb:
    ssl_verify_mode: ":verify_none"
#  http_proxy: http://10.0.2.2:8888
#  https_proxy: http://10.0.2.2:8888
#  ftp_proxy: http://10.0.2.2:8888
#  no_proxy: 'localhost,127.0.0.1,10.0.2.,33.33.33.,.localdomain.com'
#  ----------------------------------------------------------------
#  http_proxy: http://username:password@proxy.domain.com:8000
#  https_proxy: https://username:password@proxy.domain.com:8000
#  no_proxy: 'localhost,127.0.0.1,.localdomain.com'

platforms:
  - name: centos-6.7
  - name: centos-7.2
  - name: ubuntu-14.04
  - name: ubuntu-15.04
  - name: windows-2008r2
  - name: windows-2012r2

suites:
  - name: core_base
    environment: "core_base"
    run_list:
      - role[base]
    attributes: {}
    includes: ['centos-6.7', 'centos-7.2', 'windows-2008r2', 'windows-2012r2']
  - name: core_web_apache
    environment: "core_web_apache"
    run_list:
      - role[web]
    attributes: {}
    includes: ['centos-6.7', 'centos-7.2']
