---

driver:
  name: ec2
  shared_credentials_profile: stelligentlabs
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  instance_type: t2.micro
  region: us-west-2
  security_group_ids:
    - sg-1dc02778
  subnet_id: subnet-af5c02e9
  vpc_id: vpc-15c2d077
  require_chef_omnibus: 12.5.1
  iam_profile_name: ec2-base-policy
  driver_config:
    ssl_verify_mode: ":verify_none"
  data_bags_path: "data_bags"
  encrypted_data_bag_secret_key_path: "data_bags/encrypted_data_bag_secret"
  roles_path: "roles"
  environments_path: "environments"

transport:
  username: ec2-user
  ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
platforms:
  - name: amzn2015091
    driver:
      image_id: ami-f0091d91
      tags:
        Name: testkitchen-corebase-amazon-<%= ENV['USER'] %>
        Created-By: Test Kitchen
        ApplicationName: Chef Core
        EnvironmentName: Dev
        OWNER: <%= ENV['USER'] %>
  - name: centos6
    driver:
      image_id: ami-07d4f737
      tags:
        Name: testkitchen-corebase-centos6-<%= ENV['USER'] %>
        Created-By: Test Kitchen
        ApplicationName: Chef Core
        EnvironmentName: Dev
        OWNER: <%= ENV['USER'] %>
  - name: centos7
    driver:
      image_id: ami-07e6c437
      tags:
        Name: testkitchen-corebase-centos7-<%= ENV['USER'] %>
        Created-By: Test Kitchen
        ApplicationName: Chef Core
        EnvironmentName: Dev
        OWNER: <%= ENV['USER'] %>
  - name: rhel6
    driver:
      image_id: ami-0b5f073b
      tags:
        Name: testkitchen-corebase-rhel6-<%= ENV['USER'] %>
        Created-By: Test Kitchen
        ApplicationName: Chef Core
        EnvironmentName: Dev
        OWNER: <%= ENV['USER'] %>
  - name: rhel7
    driver:
      image_id: ami-775e4f16
      tags:
        Name: testkitchen-baselinux-rhel7-<%= ENV['USER'] %>
        Created-By: Test Kitchen
        ApplicationName: Chef Core
        EnvironmentName: Dev
        OWNER: <%= ENV['USER'] %>
  - name: ubuntu1404
    driver:
      image_id: ami-9abea4fb
      tags:
        Name: testkitchen-corebase-ubuntu1404-<%= ENV['USER'] %>
        Created-By: Test Kitchen
        ApplicationName: Chef Core
        EnvironmentName: Dev
        OWNER: <%= ENV['USER'] %>
  - name: win2008r2
    driver:
      image_id: ami-3e88a354
      tags:
        Name: testkitchen-corebase-windows-2008r2-<%= ENV['USER'] %>
        Created-By: Test Kitchen
        ApplicationName: Chef Core
        EnvironmentName: Dev
        OWNER: <%= ENV['USER'] %>
  - name: win2012r2
    driver:
      image_id: ami-43193029
      tags:
        Name: testkitchen-corebase-windows-2012r2-<%= ENV['USER'] %>
        Created-By: Test Kitchen
        ApplicationName: Chef Core
        EnvironmentName: Dev
        OWNER: <%= ENV['USER'] %>

suites:
  - name: base_rh
    data_bags_path: "test/integration/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/data_bags/encrypted_data_bag_secret"
    run_list:
      - recipe[bonusbits_linux_base]
    attributes: {}
    includes: ['amzn2015091', 'centos6', 'centos7', 'rhel6', 'rhel7']
  - name: base_deb
    data_bags_path: "test/integration/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/data_bags/encrypted_data_bag_secret"
    run_list:
      - recipe[bonusbits_linux_base]
    attributes: {}
    includes: ['ubuntu1404']
suites:
  - name: core_base
    environment: "core_base"
    run_list:
      - role[base]
    attributes: {}
    includes: ['amzn2015091', 'centos6', 'centos7', 'rhel6', 'rhel7', 'windows-2008r2', 'windows-2012r2']
  - name: core_web_apache
    environment: "core_web_apache"
    run_list:
      - role[web]
    attributes: {}
    includes: ['centos-6.7', 'centos-7.2']