source 'https://rubygems.org'

# gem 'berkshelf', '> 3.0.0'
# gem 'chef', '~> 12.0'
# gem 'chef-zero', '> 3.2.0'
# gem 'foodcritic', '> 4.0.0'
# gem 'rubocop', '> 0.29.0'
# gem 'chefspec', '> 4.2.0'
# gem 'test-kitchen', '> 1.3.0'
# gem 'kitchen-vagrant', '> 0.15.0'
# gem 'knife-spork', '> 1.5.0'
# gem 'fauxhai', '> 2.3.0'
# gem 'chef-dk', '> 0.4.0'